spring:
  application:
    name: microservice-consumer-movie-fegin
server:
  port: 7901
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
  instance: 
    preferIpAddress: true