spring:
  application:
    name: microservice-consumer-movie-ribbon
server:
  port: 8080
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
  instance: 
    preferIpAddress: true