server:
  port: 8040
spring:
  application:
    name: microservice-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
#方式1
#zuul:
#  ignoredServices: microservice-consumer-movie-ribbon-with-hystrix
#  routes:
#    microservice-provider-user: /user/**
#方式2
#zuul:
#  routes:
#    abc:
#      path: /user-path/**
#      serviceId: microservice-provider-user
#方式3
#zuul:
#  routes:
#    abc:
#      path: /user-url/**
#      url: http://10.6.222.99:7800/
#方式4
zuul:
  routes:
    abc:
      path: /user-path/**
      serviceId: microservice-provider-user
ribbon:
  eureka:
    enabled: false
microservice-provider-user:     # 这边是ribbon要请求的微服务的serviceId
  ribbon:
    listOfServers: http://localhost:7800,http://localhost:7801   

    
    