security:
  basic:
    enabled: true
  user:
    name: root
    password: root  
server:
  port: 8761
spring:
  application:
    name: microservice-provider-user
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/
 