spring:
  application:
    name: microservice-consumer-movie-ribbon-with-hystrix-propagation
server:
  port: 8082
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
  instance: 
    preferIpAddress: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000